# numpy: arrays and functions

## 9/16/2020

<a href="?print-pdf">print view</a>

In [1]:
%%html

<script src="http://bits.csb.pitt.edu/asker.js/lib/asker.js"></script>

<script>

require(['https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.js'], function(Ch){
 Chart = Ch;
});

$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');


//the callback is provided a canvas object and data 
var chartmaker = function(canvas, labels, data) {
  var ctx = $(canvas).get(0).getContext("2d");
     var dataset = {labels: labels,                     
    datasets:[{
     data: data,
     backgroundColor: "rgba(150,64,150,0.5)",
         fillColor: "rgba(150,64,150,0.8)",    
  }]};
  var myBarChart = new Chart(ctx,{type:'bar',data:dataset,options:{legend: {display:false},scales:{yAxes:[{ticks:{min: 0}}]}}});


};

$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();



</script>

In [3]:
%%html
<div id="dogq" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#dogq';
	jQuery(divid).asker({
	    id: divid,
	    question: "How do you feel about dogs?",
		answers: ["Love them", "They're okay", "Make me nervous","Do not like"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

# Arrays

`numpy` arrays are dense, continuous, uniformly sized blocks of identically typed data values

In [4]:
import numpy as np
L = [[0,1],[2,3]]
A = np.array(L)

In [5]:
print("L:",L)
print("A:\n",A)

L: [[0, 1], [2, 3]]
A:
 [[0 1]
 [2 3]]


In [6]:
print(type(L),type(A))

<class 'list'> <class 'numpy.ndarray'>


# Array Memory Layout

<center><img src='imgs/memarray.png'></center>

# Array Memory

In the standard python interpretter, the return value of `id` is the memory address of the object.

In [7]:
print(id(L))

140398081326784


In [8]:
print(id(L[1])-id(L[0])) #rows are far away

273920


In [9]:
print(id(L[0][1])-id(L[0][0])) #columns not so much, but 32 bytes?

32


# Why does this matter?

Keeping data close together results in faster access times.
 * It's easier to figure out the location of the data
 * The data is more likely to fit in the processor's *cache*

## If you have a *block* of *dense* numerical data, store it in a `numpy` array

# Creating `numpy` Arrays

Note that `np.ndarray` and `np.array` are the same thing.

In [10]:
A = np.array([1,2,3,4])
A.dtype #type of what is stored in the array - NOT python types!

dtype('int64')

In [11]:
A.ndim #number of dimensions (axes in numpy speak)


1

In [12]:
A.shape #size of the dimensions as a tuple

(4,)

In [13]:
A.reshape((4,1)).shape #a column vector

(4, 1)

In [28]:
%%html
<div id="numpyi8" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpyi8';
	jQuery(divid).asker({
	    id: divid,
	    question: "How much space does an int8 take up?",
		answers: ["1 byte","8 bytes","64 bytes","4 bytes"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

In [29]:
%%html
<div id="numpyi8z" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpyi8z';
	jQuery(divid).asker({
	    id: divid,
	    question: "What is the largest number a int8 can store?",
		answers: ["127","128","255","256","inf"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

In [30]:
A = np.array([1,2,3,4]).reshape(4,1)

In [31]:
%%html
<div id="numpydim" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpydim';
	jQuery(divid).asker({
	    id: divid,
	    question: "How many dimensions (axes) does A have?",
		answers: ["0","1","2","3","4"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

# Initializing numpy Arrays

In [32]:
#can initialize an array with a list, or list of lists (or list of lists of lists, etc)
M = np.array([[1,2,3],[4,5,6.0]])
print(M.dtype,M.shape)

float64 (2, 3)


In [33]:
#if know the size, but not the data, can initialize to zeros:
Z = np.zeros((10,10))
#or ones
O = np.ones((5,10))
#or identity
I = np.identity(3) #this makes a 3x3 square identity matrix

In [34]:
print(Z.dtype) #note, default type is floating point

float64


In [35]:
Z = np.zeros((10,10),np.int64) #can change
print(Z.dtype)

int64


# Indexing and Slicing

`numpy` arrays can be indexed and sliced a lot like python lists, but take **tuples** of values to reference each dimension.

In [36]:
M = np.array([[0,1,2],[3,4,5]])
M

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
print(M[1,1]) #indexing
print(M[0,-1]) #last item of first row

4
2


In [38]:
print(M[0,1:]) #can have slices - all but first column of first row

[1 2]


In [39]:
print(M[1],M[1,:]) #missing indices are treated as complete slices

[3 4 5] [3 4 5]


In [40]:
M = [ [0,1,2],[3,4,5]]

In [41]:
%%html
<div id="numpytrick" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpytrick';
	jQuery(divid).asker({
	    id: divid,
	    question: "What does M[1,1] return?",
		answers: ["0","1","2","3","4","5","Error"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

# Advanced Slicing: Integer

`numpy` arrays support advanced indexing by arrays of integers or booleans:

In [42]:
A = np.array([0,1,4,9,16,25])

In [43]:
print(A[[2,5]]) #choose just indices 2 and 5

[ 4 25]


# Advanced Slicing: Boolean

Indexing by **Boolean** *numpy arrays* can be used to select elements

In [44]:
b = A > 4
print(b)

[False False False  True  True  True]


In [45]:
print(A[b])

[ 9 16 25]


# Slicing Assignment

In [46]:
print("b =",b)
A[b] = 0

b = [False False False  True  True  True]


In [47]:
print(A)

[0 1 4 0 0 0]


In [48]:
S = np.array(['a','b','c','b','a'])
S[S != 'a'] = 'z'

In [49]:
%%html
<div id="numpytrick2" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpytrick2';
	jQuery(divid).asker({
	    id: divid,
	    question: "What is the value of S (concatenated together)?",
		answers: ["abcba","abzba","azzza","z","Error"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

# Array Views vs. Copies

 * A `numpy` array object has a pointer to a dense block of memory that stores the data of the array.
 * *Basic* slices are just *views* of this data - they are **not** a new copy. 
 * Binding the same object to different variables will **not** create a copy.
 * *Advanced* slices will create a copy if bound to a new variable - these are cases where the result may contain elements that are not contiguous in the original array 

# Views

In [50]:
A = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [51]:
B = A #A and B reference the _same_ object
A is B

True

In [52]:
B[0,0] = 1000
A

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8]])

# Sliced Views

In [53]:
row = A[1,:]
row

array([3, 4, 5])

In [54]:
row[2] = 5000
A

array([[1000,    1,    2],
       [   3,    4, 5000],
       [   6,    7,    8]])

# Explicit Copy

In [55]:
newMat = A.copy() #this will actually copy the data
newMat[0,0] = 0
A

array([[1000,    1,    2],
       [   3,    4, 5000],
       [   6,    7,    8]])

In [56]:
newMat

array([[   0,    1,    2],
       [   3,    4, 5000],
       [   6,    7,    8]])

# Advanced Slices Copy

In [57]:
A = np.array([[0,1,2],[3,4,5],[6,7,8]])
B = A[A > 4]
B

array([5, 6, 7, 8])

In [58]:
B[:] = -1
B

array([-1, -1, -1, -1])

In [59]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

but...

In [60]:
A[A > 4] = -1
A

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1]])

In [61]:
def z(M):
    M[:] = 0
A = np.array([1,2,3])
z(A)

In [62]:
%%html
<div id="numpyA" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpyA';
	jQuery(divid).asker({
	    id: divid,
	    question: "What is the value of A?",
		answers: ["[0 0 0]","[1 2 3]","[0 2 3]","Error"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

# Functions on Arrays

`numpy` includes a number of standard functions that will work on arrays

In [63]:
A = [1,2,3,4]
np.mean(A)

2.5

In [64]:
np.sum(A)

10

In [65]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Axis

Most aggregation operations take an `axis` parameter that limits the operation to a specific direction in the array
* axis 0: across rows (apply operation to individual columns)
* axis 1: across columns (apply operation to individual rows)

In [66]:
b = np.arange(12).reshape(3,4); b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.sum(b)

66

In [68]:
np.sum(b,axis=0)

array([12, 15, 18, 21])

In [69]:
np.sum(b,axis=1)

array([ 6, 22, 38])

In [71]:
%%html
<div id="numpyaxis" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#numpyaxis';
	jQuery(divid).asker({
	    id: divid,
	    question: "How would I compute the largest column average of b?",
		answers: ["np.max(np.mean(b))","np.mean(np.max(b,axis=1))","np.max(np.mean(b,axis=0))","np.max(np.mean(b,axis=1))"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

# Data Normalization

## Q1: How would you rescale your data to range from 0 to 1?

## Q2: How would you rescale your data to have zero mean and unit standard deviation?

# Loading Data

`genfromtxt` (and the simpler `loadtxt`) will read in deliminated files.

In [72]:
np.genfromtxt('../files/Spellman.csv')

array([nan, nan, nan, ..., nan, nan, nan])

The defaul delimiter is *whitespace* which will not work with a csv

In [73]:
np.genfromtxt('../files/Spellman.csv',delimiter=',')

array([[           nan,  4.0000000e+01,  5.0000000e+01, ...,
         2.4000000e+02,  2.5000000e+02,  2.6000000e+02],
       [           nan, -7.0000000e-02, -2.3000000e-01, ...,
         5.7000000e-01,  0.0000000e+00,  1.0000000e-02],
       [           nan,  2.1500000e-01,  9.0000000e-02, ...,
        -1.0000000e-01,  2.7000000e-01,  2.3500001e-01],
       ...,
       [           nan, -2.5500000e-01, -3.6000000e-01, ...,
         8.4000000e-01, -3.9000000e-01, -4.1500000e-01],
       [           nan,  5.7000000e-01,  1.2000000e-01, ...,
        -1.2000000e-01,  6.9000000e-01,  5.5500000e-01],
       [           nan,  4.0500000e-01,  1.7000000e-01, ...,
        -8.0000000e-02,  6.5000000e-01,  5.2000000e-01]])

Why nan? 

# Loading Data

Recall that numpy arrays are dense, uniformly typed arrays.  Can't mix a gene name (string) with expression values (float).

In [75]:
strdata = np.genfromtxt('../files/Spellman.csv',dtype=str,delimiter=',')
strdata

array([['time', '40', '50', ..., '240', '250', '260'],
       ['YAL001C', '-0.07', '-0.23', ..., '0.57', '0', '0.01'],
       ['YAL014C', '0.215', '0.09', ..., '-0.1', '0.27', '0.23500001'],
       ...,
       ['YPR201W', '-0.255', '-0.36', ..., '0.84', '-0.39', '-0.415'],
       ['YPR203W', '0.57', '0.12', ..., '-0.12', '0.69', '0.555'],
       ['YPR204W', '0.405', '0.17', ..., '-0.08', '0.65', '0.52']],
      dtype='<U12')

In [77]:
header = strdata[0,1:].astype(int)
genes = strdata[1:,0]
values = strdata[1:,1:].astype(float)

In [78]:
len(strdata),len(strdata[0])

(4382, 24)

In [79]:
%%html
<div id="strdatashape" style="width: 500px"></div>
<script>
$('head').append('<link rel="stylesheet" href="http://bits.csb.pitt.edu/asker.js/themes/asker.default.css" />');

    var divid = '#strdatashape';
	jQuery(divid).asker({
	    id: divid,
	    question: "What is the shape of genes?",
		answers: ["(4381,1)","(4381,)","(4381,24)","(4382,1)"],
        server: "http://bits.csb.pitt.edu/asker.js/example/asker.cgi",
		charter: chartmaker})
    
$(".jp-InputArea .o:contains(html)").closest('.jp-InputArea').hide();


</script>

In [80]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strin

# Project: Expression Data

https://asinansaglam.github.io/python_bio_2022/files/Spellman.csv

* Read this data into a numpy array
* Plot a histogram of the expression values for the first time point
* Plot a histogram of the expression values for the last time point
* Plot a histogram of the average expression value for the genes across all time points
* Plot the average expression value (across all genes) at each time point as a line graph
* Plot two series of average expression values: one for all genes where the first value is positive and the other for all genes where the first value is negative
